### ISSUE TITLE
see all birthdays by month in a single file

### ISSUE THREAD

**Issue by ronniemyers** [thephm/hal_md#1]
There may be some use cases where someone wants to use a single markdown file `Birthday.md` to see all birthdays by month.

Example: 

# January
`[/^(birthday)/: /.*01-\d{2}$/]`

# February
`[/^(birthday)/: /.*02-\d{2}$/]`

etc...

**Comment by thephm** [comment]
Great idea thanks! And thanks for the improved regex, I'm so weak with regex that I used ChatGPT to help me create them 🤣

**Comment by thephm** [comment]
I've been working on a Python script for this and had some success, sample output;

https://github.com/thephm/sample/blob/7d4f65dd51e14f2e8d772b9ce6c4778145076f21/Computer%20Science%20People's%20Birthdays.md

**Comment by thephm** [comment]
![Computer Science People's Birthdays.png](https://github.com/thephm/hal_md/assets/8527588/53e2f9b3-523f-4523-8602-8f06e1557034)

After a few mins work putting on a canvas in Obsidian
